### PR TITLE
fix: More robustly escape input character

### PR DESCRIPTION
**Pull request by srebhan**
When using inputs that do have a meaning in RegExp, e.g
```shell
# This is a special comment (I want it to show in the clip!) pointing to an URL https//mysite.org?some=value&sort=true
```
the current code fails with reporting an invalid value.

This PR fixes the issue by consequently escaping input characters like brackets etc.

### CODE REVIEW

**Comment by PierreMarchand20** [comment]
I am not sure to understand what you are trying to solve. Could you give an example with the input file, the output you want and the error you get ?

**Comment by srebhan** [comment]
I don't have access to the failing file currently due to travel. Will post an example next week...

**Comment by GirZ0n** [comment]
Hi, @PierreMarchand20! I think I have the same problem as @srebhan. I have a simple calculator app and this input file:
```bash
#$ expect : 
abracadabra
#$ expect \n
+
#$ expect : 
ahalai
#$ expect \n
mahalai
#$ expect \n
69
#$ expect : 
avada kedavra
#$ expect \n
42
#$ expect : 
#$ sendcontrol c
```

If I run your tool like this:
```bash
asciinema-automation -aa "-c \"java -jar ./Main.jar\"" --debug ./script.sh ./out.cast
```
I'll get this error:
```bash
Traceback (most recent call last):
  File "/home/girz0n/PycharmProjects/anderson/.venv/bin/asciinema-automation", line 33, in <module>
    sys.exit(load_entry_point('asciinema-automation==0.0.1', 'console_scripts', 'asciinema-automation')())
  File "/home/girz0n/PycharmProjects/anderson/.venv/lib/python3.8/site-packages/asciinema_automation/cli.py", line 59, in cli
    script.execute()
  File "/home/girz0n/PycharmProjects/anderson/.venv/lib/python3.8/site-packages/asciinema_automation/script.py", line 143, in execute
    instruction.run(self)
  File "/home/girz0n/PycharmProjects/anderson/.venv/lib/python3.8/site-packages/asciinema_automation/instruction.py", line 96, in run
    super().run(script)
  File "/home/girz0n/PycharmProjects/anderson/.venv/lib/python3.8/site-packages/asciinema_automation/instruction.py", line 69, in run
    script.process.expect(str(receive_character))
  File "/home/girz0n/PycharmProjects/anderson/.venv/lib/python3.8/site-packages/pexpect/spawnbase.py", line 342, in expect
    compiled_pattern_list = self.compile_pattern_list(pattern)
  File "/home/girz0n/PycharmProjects/anderson/.venv/lib/python3.8/site-packages/pexpect/spawnbase.py", line 232, in compile_pattern_list
    compiled_pattern_list.append(re.compile(p, compile_flags))
  File "/usr/local/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/local/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/local/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/local/lib/python3.8/sre_parse.py", line 668, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
```
this out.cast file:
```
{"version": 2, "width": 80, "height": 24, "timestamp": 1684237900, "env": {"SHELL": "/bin/bash", "TERM": "xterm-256color"}}
[0.035106, "o", "Welcome to a simple Kotlin calculator!\r\n\r\n"]
[0.0471, "o", "Please enter the operator (possible values: +, -, *, /): "]
[0.412981, "o", "a"]
[0.701222, "o", "b"]
[0.951586, "o", "r"]
[1.160468, "o", "a"]
[1.359893, "o", "c"]
[1.586432, "o", "a"]
[1.74398, "o", "d"]
[1.995145, "o", "a"]
[2.198514, "o", "b"]
[2.315877, "o", "r"]
[2.514657, "o", "a"]
[2.71957, "o", "\r\n"]
[2.720946, "o", "Incorrect operator (possible values: +, -, *, /).\r\n"]
[3.130576, "o", "+"]
```
and this out.log file:
```
INFO:root:asciinema rec out.cast -c "java -jar ./Main.jar"
DEBUG:root:b"\x1b[0;32masciinema: exit opened program when you're done\x1b[0m\r"
DEBUG:root:b'\n'
INFO:root:Start reading instructions
INFO:root:ExpectInstruction
DEBUG:root:Expect ':'
INFO:root:SendShellInstruction
DEBUG:root:Send 'abracadabra'
DEBUG:root:Send '\n'
INFO:root:ExpectInstruction
DEBUG:root:Expect '\n'
INFO:root:SendShellInstruction
DEBUG:root:Send '+'
```

But if I use srebhan's fix, then everything will be normal:
dark

**Comment by srebhan** [comment]
@PierreMarchand20 here is a minimal example
```shell
#$ sendcharacter #
 This is a test with URL (https://github.com)
exit
```
triggering
```text
Traceback (most recent call last):
  File "/home/sven/env/bin/asciinema-automation", line 8, in <module>
    sys.exit(cli())
  File "/home/sven/env/lib/python3.10/site-packages/asciinema_automation/cli.py", line 61, in cli
    script.execute()
  File "/home/sven/env/lib/python3.10/site-packages/asciinema_automation/script.py", line 150, in execute
    instruction.run(self)
  File "/home/sven/env/lib/python3.10/site-packages/asciinema_automation/instruction.py", line 97, in run
    super().run(script)
  File "/home/sven/env/lib/python3.10/site-packages/asciinema_automation/instruction.py", line 70, in run
    script.process.expect(str(receive_character))
  File "/home/sven/env/lib/python3.10/site-packages/pexpect/spawnbase.py", line 342, in expect
    compiled_pattern_list = self.compile_pattern_list(pattern)
  File "/home/sven/env/lib/python3.10/site-packages/pexpect/spawnbase.py", line 232, in compile_pattern_list
    compiled_pattern_list.append(re.compile(p, compile_flags))
  File "/usr/lib/python3.10/re.py", line 251, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.10/sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.10/sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.10/sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.10/sre_parse.py", line 843, in _parse
    raise source.error("missing ), unterminated subpattern",
re.error: missing ), unterminated subpattern at position 0
```

with the PR proposed, the script runs as expected.

**Comment by PierreMarchand20** [comment]
Hi, thank you for your contribution @srebhan, and thank you for your help @GirZ0n. I know understand the issue, and this is indeed more robust, and way smarter than before :-) 

I will soon merge this PR, but before that, I want to add some CI to this repo to avoid any breaking change. I should do that this week, so hopefully this PR should be merged by the end of the week and the PyPI version updated.

**Comment by PierreMarchand20** [comment]
It is taking longer than expected, but I have not forgotten :-)

**Pull request merged**
