### PR TITLE
Change standart to standard

### PR DESCRIPTION
**Pull request by punchagan**
Thank you for this project. This is a nitpick, but hopefully useful.

### CODE REVIEW

**Comment by PierreMarchand20** [comment]
Good point :-) thank you!

**Comment by PierreMarchand20** [comment]
Something broke in CI, but it should not be related to your modifications. I tried to setup a CI checking the output of asciinema on some examples, but it is difficult to have a reproductible and robust output. If that's ok, I will try to fix it directly in your PR.

**Comment by punchagan** [comment]
> If that's ok, I will try to fix it directly in your PR.

Sure, go ahead!

**Comment by PierreMarchand20** [comment]
Not as es easy I thought, but I fixed the CI and just merged your PR. Thank you for your contribution!

**Pull request merged**
